// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj6hB-c_c4isdIZyqDAYdHxw3yPa39CnU',
    appId: '1:151129393806:web:4e1e756e9d1a79836d97df',
    messagingSenderId: '151129393806',
    projectId: 'aula5-uninter',
    authDomain: 'aula5-uninter.firebaseapp.com',
    databaseURL: 'https://aula5-uninter-default-rtdb.firebaseio.com',
    storageBucket: 'aula5-uninter.firebasestorage.app',
    measurementId: 'G-D5XP0SKWMR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1V_U3h3TM75bPuLXw2mW2gEUrW2aOK0c',
    appId: '1:151129393806:android:74451d8331c030486d97df',
    messagingSenderId: '151129393806',
    projectId: 'aula5-uninter',
    databaseURL: 'https://aula5-uninter-default-rtdb.firebaseio.com',
    storageBucket: 'aula5-uninter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYvhEfobqLtO8fN5UT-EJhW7RcOFnQoXw',
    appId: '1:151129393806:ios:0591689f27c6c1d06d97df',
    messagingSenderId: '151129393806',
    projectId: 'aula5-uninter',
    databaseURL: 'https://aula5-uninter-default-rtdb.firebaseio.com',
    storageBucket: 'aula5-uninter.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYvhEfobqLtO8fN5UT-EJhW7RcOFnQoXw',
    appId: '1:151129393806:ios:0591689f27c6c1d06d97df',
    messagingSenderId: '151129393806',
    projectId: 'aula5-uninter',
    databaseURL: 'https://aula5-uninter-default-rtdb.firebaseio.com',
    storageBucket: 'aula5-uninter.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBj6hB-c_c4isdIZyqDAYdHxw3yPa39CnU',
    appId: '1:151129393806:web:11327904712c8fad6d97df',
    messagingSenderId: '151129393806',
    projectId: 'aula5-uninter',
    authDomain: 'aula5-uninter.firebaseapp.com',
    databaseURL: 'https://aula5-uninter-default-rtdb.firebaseio.com',
    storageBucket: 'aula5-uninter.firebasestorage.app',
    measurementId: 'G-JRHSC3EVR1',
  );

}